version: '3.8'

services:

        elastic:
                image: "docker.elastic.co/elasticsearch/elasticsearch:7.6.2"
                restart: always
                container_name: elastic
                networks: ["tira"]
                ports:
                        - "9200:9200"
                volumes:
                        - type: bind
                          source: ./indexing/elasticsearch_data
                          target: /usr/share/elasticsearch/data
                environment:
                        - discovery.type=single-node
                healthcheck:
                        test: ["CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health"]
        index:
          build: .
          container_name: index
          networks: ["tira"]
          volumes:
                  - .:/pred
          healthcheck:
            test: [ "CMD", "curl", "-f", "http://elastic:9200" ]
            interval: 30s
            timeout: 10s
            retries: 5

networks:
        tira: