version: '3.8'

services:

        elastic:
                image: "docker.elastic.co/elasticsearch/elasticsearch:7.6.2"
                restart: always
                container_name: elastic
                networks: ["tira"]
                ports:
                        - "9200:9200"
                volumes:
                        - type: bind
                          source: ./indexing/elasticsearch_data
                          target: /usr/share/elasticsearch/data
                environment:
                        - discovery.type=single-node
                healthcheck:
                        test: ["CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health"]
        python:
                build: ./deploy/python
                container_name: python
                restart: always
                networks: ["tira"]
                ports:
                        - "8888:8888"
                environment:
                        - GRANT_SUDO=yes
                user: root
                volumes:
                        - type: bind
                          source: .
                          target: /root
                        - type: bind
                          source: ../data
                          target: /media
                        - type: bind
                          source: /tmp
                          target: /tmp
                depends_on:
                        - elastic
                working_dir: /root
        searchengine:
          build: ./deploy/indexing
          container_name: indexing
          networks: [ "tira" ]
          volumes:
            - .:/pred


networks:
        tira: