version: '3.8'

services:

        elastic:
                image: "docker.elastic.co/elasticsearch/elasticsearch:7.6.2"
                restart: always
                container_name: elastic
                networks: ["tira"]
                ports:
                        - "9200:9200"
                volumes:
                        - type: bind
                          source: ./indexing/elasticsearch_data
                          target: /usr/share/elasticsearch/data
                environment:
                        - discovery.type=single-node
                healthcheck:
                        test: ["CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health"]
        searchengine:
          build: .
          container_name: searchengine
          networks: ["tira"]
          volumes:
                  - .:/pred
          ports:
                  - "5000:5000"
          healthcheck:
            test: [ "CMD", "curl", "-f", "http://searchengine:5000" ]
            interval: 30s
            timeout: 10s
            retries: 5

        evaluation:
          build: ./deploy/evaluation
          container_name: evaluation
          networks: [ "tira" ]
          volumes:
            - .:/pred


networks:
        tira: